# Generated by Django 5.2.1 on 2025-06-01 20:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psrs_recruitment_auth', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
