# Generated by Django 5.2.1 on 2025-06-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psrs_recruitment_auth', '0004_profile_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('applicant', 'Applicant'), ('recruiter', 'Recruiter'), ('admin', 'Admin')], default='applicant', help_text='Select the type of user.', max_length=10),
        ),
    ]
