# Generated by Django 5.2.1 on 2025-05-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psrs_recruitment', '0003_application_created_by_application_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('REMOTE', 'Remote'), ('DAR ES SALAAM', 'Dar es Salaam'), ('OTHER', 'Other')], default='OTHER', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(default='Requirements'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(default='Responsibilities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
