# Generated by Django 5.2.1 on 2025-05-21 03:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psrs_recruitment', '0004_job_location_job_requirements_job_responsibilities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='requirements',
            new_name='qualifications',
        ),
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
