# Generated by Django 5.2.1 on 2025-05-21 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psrs_recruitment', '0005_rename_requirements_job_qualifications_job_deadline'),
        ('psrs_recruitment_auth', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psrs_recruitment_auth.profile'),
        ),
    ]
