# Generated by Django 5.2.1 on 2025-06-01 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psrs_recruitment', '0007_alter_application_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
    ]
