# Generated by Django 5.2.1 on 2025-06-01 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psrs_recruitment', '0009_application_unique_id_job_unique_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at']},
        ),
    ]
