# Generated by Django 5.2.1 on 2025-06-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psrs_recruitment', '0010_alter_application_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('REMOTE', 'Remote'), ('DAR_ES_SALAAM', 'Dar es Salaam'), ('OTHER', 'Other')], default='OTHER', max_length=255),
        ),
    ]
