# Generated by Django 5.2.1 on 2025-05-21 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psrs_recruitment_setting', '0002_company_created_by_company_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='psrs_recrui_name_31b6e4_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['email'], name='psrs_recrui_email_1b0f81_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['phone_number'], name='psrs_recrui_phone_n_10faec_idx'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('phone_number',), name='unique_phone_number'),
        ),
    ]
